// vue/src/App.vue
<script setup>
import { ref, computed, watchEffect } from "vue";

const STORAGE_KEY = "todos-vue";

const filters = {
  all: (todos) => todos,
  active: (todos) => todos.filter((todo) => !todo.completed),
  completed: (todos) => todos.filter((todo) => todo.completed)
};

const todos = ref(JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]"));
const visibility = ref("all");
const editedTodo = ref();

const filteredTodos = computed(() => filters[visibility.value](todos.value));
const remaining = computed(() => filters.active(todos.value).length);

function toggleAll(e) {
  todos.value.forEach((todo) => (todo.completed = e.target.checked));
}

function addTodo(e) {
  const value = e.target.value.trim();
  if (value) {
    todos.value.push({
      id: Date.now(),
      title: value,
      completed: false
    });
    e.target.value = "";
  }
}

function removeTodo(todo) {
  todos.value.splice(todos.value.indexOf(todo), 1);
}

let beforeEditCache = "";

function editTodo(todo) {
  beforeEditCache = todo.title;
  editedTodo.value = todo;
}

function cancelEdit(todo) {
  editedTodo.value = null;
  todo.title = beforeEditCache;
}

function doneEdit(todo) {
  if (editedTodo.value) {
    editedTodo.value = null;
    todo.title = todo.title.trim();
    if (!todo.title) removeTodo(todo);
  }
}

function removeCompleted() {
  todos.value = filters.active(todos.value);
}

watchEffect(() => {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(todos.value));
});

function onHashChange() {
  const route = window.location.hash.replace(/#\/?/, "");
  if (filters[route]) {
    visibility.value = route;
  } else {
    window.location.hash = "";
    visibility.value = "all";
  }
}

window.addEventListener("hashchange", onHashChange);
onHashChange();
</script>

<template>
  <div id="app">
    <section class="todoapp">
      <header class="header">
        <h1>todos</h1>
        <input
          class="new-todo"
          autofocus
          placeholder="What needs to be done?"
          @keyup.enter="addTodo"
        />
      </header>
      <section class="main" v-show="todos.length">
        <input
          id="toggle-all"
          class="toggle-all"
          type="checkbox"
          :checked="remaining === 0"
          @change="toggleAll"
        />
        <label for="toggle-all">Mark all as complete</label>
        <ul class="todo-list">
          <li
            v-for="todo in filteredTodos"
            class="todo"
            :key="todo.id"
            :class="{ completed: todo.completed, editing: todo === editedTodo }"
          >
            <div class="view">
              <input class="toggle" type="checkbox" v-model="todo.completed" />
              <label @dblclick="editTodo(todo)">{{ todo.title }}</label>
              <button class="destroy" @click="removeTodo(todo)"></button>
            </div>
            <input
              v-if="todo === editedTodo"
              class="edit"
              type="text"
              v-model="todo.title"
              @vue:mounted="({ el }) => el.focus()"
              @blur="doneEdit(todo)"
              @keyup.enter="doneEdit(todo)"
              @keyup.escape="cancelEdit(todo)"
            />
          </li>
        </ul>
      </section>
      <footer class="footer" v-show="todos.length">
        <span class="todo-count">
          <strong>{{ remaining }}</strong>
          <span>{{ remaining === 1 ? "item" : "items" }} left</span>
        </span>
        <ul class="filters">
          <li>
            <a href="#/all" :class="{ selected: visibility === 'all' }">All</a>
          </li>
          <li>
            <a href="#/active" :class="{ selected: visibility === 'active' }"
              >Active</a
            >
          </li>
          <li>
            <a
              href="#/completed"
              :class="{ selected: visibility === 'completed' }"
              >Completed</a
            >
          </li>
        </ul>
        <button
          class="clear-completed"
          @click="removeCompleted"
          v-show="todos.length > remaining"
        >
          Clear completed
        </button>
      </footer>
    </section>
  </div>
</template>

// svelte-5/src/App.svelte
<script>
  const ENTER_KEY = 13;
  const ESCAPE_KEY = 27;

  let currentFilter = "all";
  let items = [];
  let editing = null;

  try {
    items = JSON.parse(localStorage.getItem("todos-svelte")) || [];
  } catch (err) {
    items = [];
  }

  const updateView = () => {
    currentFilter = "all";
    if (window.location.hash === "#/active") {
      currentFilter = "active";
    } else if (window.location.hash === "#/completed") {
      currentFilter = "completed";
    }
  };

  window.addEventListener("hashchange", updateView);
  updateView();

  function clearCompleted() {
    items = items.filter((item) => !item.completed);
  }

  function remove(index) {
    items = items.slice(0, index).concat(items.slice(index + 1));
  }

  function toggleAll(event) {
    items = items.map((item) => ({
      id: item.id,
      description: item.description,
      completed: event.target.checked
    }));
  }

  function createNew(event) {
    if (event.which === ENTER_KEY) {
      items = items.concat({
        id: Date.now(),
        description: event.target.value,
        completed: false
      });
      event.target.value = "";
    }
  }

  function handleEdit(event) {
    if (event.which === ENTER_KEY) event.target.blur();
    else if (event.which === ESCAPE_KEY) editing = null;
  }

  function submit(event) {
    items[editing].description = event.target.value;
    editing = null;
  }

  $: filtered =
    currentFilter === "all"
      ? items
      : currentFilter === "completed"
        ? items.filter((item) => item.completed)
        : items.filter((item) => !item.completed);

  $: numActive = items.filter((item) => !item.completed).length;
  $: numCompleted = items.filter((item) => item.completed).length;

  $: try {
    localStorage.setItem("todos-svelte", JSON.stringify(items));
  } catch (err) {
    // noop
  }
</script>

<header class="header">
  <h1>todos</h1>
  <input
    class="new-todo"
    on:keydown={createNew}
    placeholder="What needs to be done?"
    autofocus
  />
</header>

{#if items.length > 0}
  <section class="main">
    <input
      id="toggle-all"
      class="toggle-all"
      type="checkbox"
      on:change={toggleAll}
      checked={numCompleted === items.length}
    />
    <label for="toggle-all">Mark all as complete</label>

    <ul class="todo-list">
      {#each filtered as item, index (item.id)}
        <li
          class="{item.completed ? 'completed' : ''} {editing === index
            ? 'editing'
            : ''}"
        >
          <div class="view">
            <input
              class="toggle"
              type="checkbox"
              bind:checked={item.completed}
            />
            <label on:dblclick={() => (editing = index)}
              >{item.description}</label
            >
            <button on:click={() => remove(index)} class="destroy"></button>
          </div>

          {#if editing === index}
            <input
              value={item.description}
              id="edit"
              class="edit"
              on:keydown={handleEdit}
              on:blur={submit}
              autofocus
            />
          {/if}
        </li>
      {/each}
    </ul>

    <footer class="footer">
      <span class="todo-count">
        <strong>{numActive}</strong>
        {numActive === 1 ? "item" : "items"} left
      </span>

      <ul class="filters">
        <li>
          <a class={currentFilter === "all" ? "selected" : ""} href="#/">All</a>
        </li>
        <li>
          <a
            class={currentFilter === "active" ? "selected" : ""}
            href="#/active">Active</a
          >
        </li>
        <li>
          <a
            class={currentFilter === "completed" ? "selected" : ""}
            href="#/completed">Completed</a
          >
        </li>
      </ul>

      {#if numCompleted}
        <button class="clear-completed" on:click={clearCompleted}>
          Clear completed
        </button>
      {/if}
    </footer>
  </section>
{/if}
